out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: malnet
  entity: <redacted>
dataset:
  format: MalNetTinyFeaturesCommon # +keepisolated
  name: none+none+ldp # trim/prune/zero (+base/llm/all) (+ldp/constant/degree)
  task: graph
  task_type: classification
  transductive: False
  node_encoder: False
  edge_encoder: False
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GINModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: max
gt:
  layer_type: gcnconv
  layers: 5
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 1
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
pretrained:
  freeze_main: True
  dir: results/mnt_none+ldp_gcn
  reset_prediction_head: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 10
  scheduler: reduce_on_plateau # cosine_with_warmup
  num_warmup_epochs: 0